app/jobs/models.py
from ..database import db, SCHEMA
from flask import session
from app.user.utils import format_create_time

class Job:

    table = 'job'

    def create(self, data):
        return db.insert(SCHEMA, self.table, data)

    def update(self, data):
        return db.update(SCHEMA, self.table, data)

    def delete(self, id):
        return db.delete(SCHEMA, self.table, [id])

    def get(self, id):
        job = db.search_by_hash(SCHEMA, self.table, [id], get_attributes=['*'])[0]
        return format_create_time(job)

    @classmethod
    def get_user_by_attr(cls, attribute, value):
        return db.search_by_value(SCHEMA, cls.table, attribute, value)

    @classmethod
    def search(cls, value):
        jobs = cls.get_all()
        values = value.split(',')
        print(values)
        jobs = list(filter(lambda d : d['owner'] != session['user']['id'], jobs))
        results = []
        for job in jobs:
            for skill in job['skills']:
                for _value in values:
                    if _value.lower().strip() in skill.lower() and job not in results:
                        results.append(job)
        return results

    @classmethod
    def get_all(cls):
        jobs = db.sql(f'SELECT id, title, company, emp_type, owner, job_type, location, description, skills, __createdtime__, __updatedtime__ FROM {SCHEMA}.{cls.table} ORDER BY __createdtime__')
        return format_create_time(jobs, many=True)

app/jobs/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectMultipleField, SelectField
from wtforms.validators import DataRequired
from app.user.forms import SKILL_CHOICES


TYPE_CHOICES = ['Remote', 'On-site', 'Hybrid']
EMPLOYMENT_TYPE = ['Full-time', 'Part-time', 'Internship']

class JobForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    company = StringField('Company', validators=[DataRequired()])
    location = StringField('Location', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    skills = SelectMultipleField('Skills', choices=SKILL_CHOICES, validators=[DataRequired()])
    job_type = SelectField('Workplace Type', choices=TYPE_CHOICES, validators=[DataRequired()])
    emp_type = SelectField('Employment Type', choices=EMPLOYMENT_TYPE, validators=[DataRequired()])
    submit = SubmitField('Save')

app/jobs/__init__.py
from flask import Blueprint

jobs = Blueprint('jobs', __name__)

from . import routes

app/jobs/routes.py
from flask import render_template, redirect, url_for, flash, session, request
from . import jobs
from .forms import JobForm
from .service import JobService
from app.auth.service import UserService
from .decorators import job_owner_required
from app.auth.decorators import hiring_manager_required, developer_required, login_required
from datetime import datetime


@jobs.route('/list', methods=['GET'])
@jobs.route('/list/<string:user_id>', methods=['GET'])
def job_list(user_id=None):
    jobs = JobService.get_all()
    for job in jobs:
        job['__createdtime__'] = datetime.strptime(
            job['__createdtime__'], '%d-%m-%Y %I:%M %p').strftime('%B %d, %Y')
    return render_template('jobs/list.html', jobs=jobs)


@jobs.route('/create', methods=['GET', 'POST'])
@login_required
@hiring_manager_required
def create():
    form = JobForm()
    if form.validate_on_submit():
        job = {
            'title': form.title.data,
            'company': form.company.data,
            'location': form.location.data,
            'skills': form.skills.data,
            'job_type': form.job_type.data,
            'emp_type': form.emp_type.data,
            'description': form.description.data,
            'owner': session['user']['id'],
            'applicants': []
        }
        JobService().create(job)
        flash('New job created successfully', 'success')
        return redirect(url_for('user.profile', username=session['user']['username']))
    return render_template('jobs/job.html', form=form)


@jobs.route('/update/<string:id>', methods=['GET', 'POST'])
@login_required
@hiring_manager_required
@job_owner_required
def update(id):
    form = JobForm()
    job = JobService().get_job(id)
    if form.validate_on_submit():
        job = {
            'title': form.title.data,
            'company': form.company.data,
            'location': form.location.data,
            'skills': form.skills.data,
            'job_type': form.job_type.data,
            'emp_type': form.emp_type.data,
            'description': form.description.data,
        }
        JobService().update(id, job)
        flash('Job updated successfully', 'success')
        return redirect(url_for('user.profile', username=session['user']['username']))
    if request.method == 'GET':
        form.title.data = job['title']
        form.company.data = job['company']
        form.location.data = job['location']
        form.skills.data = job['skills']
        form.job_type.data = job['job_type']
        form.emp_type.data = job['emp_type']
        form.description.data = job['description']
    return render_template('jobs/job.html', form=form, job=job)


@jobs.route('/details/<string:id>', methods=['GET', 'POST'])
@login_required
def details(id):
    job = JobService().get_job(id)
    job['__createdtime__'] = datetime.strptime(
            job['__createdtime__'], '%d-%m-%Y %I:%M %p').strftime('%B %d, %Y')
    user = UserService().get_user(job['owner'])[0]
    return render_template('jobs/details.html', job=job, user=user)


@jobs.route('/bookmark/<string:id>', methods=['GET'])
@login_required
@developer_required
def bookmark(id):
    bookmarks = UserService().bookmark(session['user']['id'], id)
    session['user']['bookmarks'] = bookmarks[0]
    if bookmarks[1] == 'add':
        flash('Job bookmarked successfully', 'success')
    else:
        flash('Job removed from bookmark', 'info')
    return redirect(request.referrer)


@jobs.route('/apply/<string:id>', methods=['GET', 'POST'])
@login_required
@developer_required
def apply(id):
    JobService().apply(id, session['user']['id'])
    return redirect(request.referrer)

app/templates/jobs/details.html
{% extends 'layouts/main-layout.html' %}
{% block content %}
<section class="single section-sm pb-0">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="card shadow">
                    <div class="card-body text-center">
                        <h3 class="mb-3">
                            Job posted by
                        </h3>
                        <div class="mb-3">
                            <img src="https://randomuser.me/api/portraits/men/15.jpg" class="rounded" alt="...">
                        </div>
                        <h5>{{user.full_name}}</h5> 
                        <h6>@{{user.username}}</h6>
                        <a href="{{url_for('user.profile', username=user.username)}}" class="btn btn-outline-info"><i class="fas fa-comment"></i> Message</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card shadow">
                    <div class="card-body">
                        <div class="p-lg-5 p-4 bg-white">
                            <h3 class="mb-2">{{job.title}} <small class="badge badge-info">{{job.job_type}}</small></h3>
                            <h4 class="mb-5">{{job.company}} ({{job.emp_type}})</h4>
                            <h5 class="mb-3">Description</h5>
                            <p class="mb-3">{{job.description|safe}}</p>
                            <h5 class="mb-3">Skills</h5>
                            <div class="card-text mb-3">
                                {% for skill in job.skills %}
                                    <small class="badge badge-primary">{{skill}}</small>
                                {% endfor %}
                            </div>
                            <p class="post-meta border-bottom pb-3 mb-0 mt-3">Posted on {{job.__createdtime__}}</p>
                            <div class="row card-text mt-2">
                                <div class="col-6">
                                    {% if current_user.id in job.applicants %}
                                        <button class="btn btn-link text-success" disabled><i class="fas fa-check"></i> Already applied to the job</button>
                                    {% else %}
                                        <a href="{{url_for('jobs.apply', id=job.id)}}" class="btn btn-outline-primary btn-sm btn-block"><i class="fas fa-user-check"></i> Apply</a>
                                    {% endif %}
                                </div>
                                <div class="col-6">
                                    <a href="{{url_for('jobs.bookmark', id=job.id)}}" class="btn btn-outline-info btn-sm btn-block">
                                        {% if job.id in current_user.bookmarks %}
                                        <i class="fas fa-check"></i> Saved
                                        {% else %}
                                        <i class="fas fa-bookmark"></i> Save
                                        {% endif %}
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

app/templates/jobs/job.html
{% extends 'layouts/main-layout.html' %}
{% block content %}
<div class="col-md-12">
    <div class="d-flex align-items-center py-5">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-8 mx-auto">
                    <div class="card shadow-sm rounded">
                        <div class="card-body">
                            <div class="d-flex justify-content-between">
                                <h4 class="mb-3">Job Details</h4>
                            </div>
                            <form action="" method="post">
                                {{form.hidden_tag()}}
                                <div class="form-group mb-3">
                                  <label class="col-form-label">{{form.title.label}}</label>
                                  {{form.title(class='form-control', placeholder='Title')}}
                                  {% for error in form.title.errors %}
                                    <small class="text-danger">{{ error }}</small>
                                  {% endfor %}
                                </div>
                                <div class="form-group mb-3">
                                    <label class="col-form-label">{{form.company.label}}</label>
                                    {{form.company(class='form-control', placeholder='Company')}}
                                    {% for error in form.company.errors %}
                                      <small class="text-danger">{{ error }}</small>
                                    {% endfor %}
                                </div>
                                <div class="form-group">
                                    <label class="col-form-label">{{form.location.label}}</label>
                                    {{form.location(class='form-control', placeholder='Location')}}
                                    {% for error in form.location.errors %}
                                        <small class="text-danger">{{ error }}</small>
                                    {% endfor %}
                                </div> 
                                <div class="form-group">
                                    <label class="col-form-label">{{form.job_type.label}}</label>
                                    {{form.job_type(class='form-control selectpicker')}}
                                    {% for error in form.job_type.errors %}
                                        <small class="text-danger">{{ error }}</small>
                                    {% endfor %}
                                </div> 
                                <div class="form-group">
                                    <label class="col-form-label">{{form.emp_type.label}}</label>
                                    {{form.emp_type(class='form-control selectpicker')}}
                                    {% for error in form.emp_type.errors %}
                                        <small class="text-danger">{{ error }}</small>
                                    {% endfor %}
                                </div>  
                                <div class="form-group">
                                    <label class="col-form-label">{{form.skills.label}}</label>
                                    {{form.skills(class='form-control selectpicker')}}
                                    {% for error in form.skills.errors %}
                                        <small class="text-danger">{{ error }}</small>
                                    {% endfor %}
                                </div>     
                                <div class="form-group">
                                    <label class="col-form-label">{{form.description.label}}</label>
                                    {{form.description(class='form-control', placeholder='Description', id='summernote')}}
                                    {% for error in form.description.errors %}
                                        <small class="text-danger">{{ error }}</small>
                                    {% endfor %}
                                </div>
                                <div class="row">
                                    <div class="col">
                                      {{form.submit(class='btn btn-primary btn-block')}}
                                    </div>
                                    <div class="col">
                                      <button type="button" class="btn btn-outline-info btn-block" onclick="goBack()">Back</button>
                                    </div>
                                </div> 
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block js %}
<script>
    $('.selectpicker').attr("data-live-search","true");

    $('#summernote').summernote({
        tabsize: 2,
        height: 120,
        toolbar: [
          ['style', ['style']],
          ['font', ['bold', 'underline', 'clear']],
          ['color', ['color']],
          ['para', ['ul', 'ol', 'paragraph']],
          ['table', ['table']],
          ['insert', ['link']],
          ['view', ['fullscreen', 'codeview', 'help']]
        ]
    });

    function goBack() {
        window.history.back();
    }
</script>
{% endblock js %}

app/templates/jobs/list.html
{% extends 'layouts/main-layout.html' %}
{% block content %}
<section class="section">
	<div class="container">
		<div class="text-center">
			<h2 class="section-title">Posted Jobs</h2>
		</div>
		<div class="row row-cols-1 row-cols-md-3">
			<!-- topic-item -->
			{% if jobs %}
				{% for job in jobs %}
					<div class="col mb-4">
						<div class="card rounded bg-light shadow">
							<i class="fas fa-briefcase card-img-top text-center" style="font-size:96px;color:rgb(3, 3, 59);"></i>
							<div class="card-body d-block match-height">
								<div class="card-title mb-3 mt-0">{{job.title}} <small class="badge badge-info">{{job.job_type}}</small></div>
								<div class="card-subtitle mb-3">{{job.company}} - {{job.emp_type}}</div>
								<div class="card-text mb-3">
									{% for skill in job.skills %}
										<small class="badge badge-primary">{{skill}}</small>
									{% endfor %}
								</div>
								<div class="row card-text mt-2">
									<div class="col-6">
										<a href="{{url_for('jobs.details', id=job.id)}}" class="btn btn-outline-primary btn-sm btn-block"><i class="fas fa-eye"></i> View Job</a>
									</div>
									<div class="col-6">
										<a href="{{url_for('jobs.bookmark', id=job.id)}}" class="btn btn-outline-info btn-sm btn-block">
											{% if job.id in current_user.bookmarks %}
											<i class="fas fa-check"></i> Saved
											{% else %}
											<i class="fas fa-bookmark"></i> Save
											{% endif %}
										</a>
									</div>
								</div>
							</div>
							<div class="card-footer">
								<small class="text-muted">Posted on {{job.__createdtime__}}</small>
							</div>						  
						</div>
					</div>
				{% endfor %}
			{% endif %}
		</div>
	</div>
</section>
{% endblock content %}