app/user/models.py
from datetime import datetime
from ..database import db, SCHEMA
from .utils import format_chat_list, format_create_time


class Profile:

    table = 'profile'

    def create(self, data):
        return db.insert(SCHEMA, self.table, data)

    def update(self, data):
        return db.update(SCHEMA, self.table, data)

    def get_by_id(self, id):
        return db.search_by_hash(SCHEMA, self.table, id)[0]

    def get_by_user_id(self, user_id):
        return db.sql(f"SELECT * FROM {SCHEMA}.{self.table} WHERE user_id='{user_id[0]}'")[0]


class Experience:

    table = 'experience'

    def create(self, data):
        return db.insert(SCHEMA, self.table, data)

    def update(self, data):
        return db.update(SCHEMA, self.table, data)

    def get_by_id(self, id):
        return db.search_by_hash(SCHEMA, self.table, id)[0]

    def get_by_user_id(self, user_id, page={'profile':None, 'all':None}):
        experiences = db.sql(f"SELECT * FROM {SCHEMA}.{self.table} WHERE user_id='{user_id[0]}'")
        experiences = sorted(experiences, key=lambda d: datetime.strptime(d['start_date'], '%d-%m-%Y'), reverse=True)
        if 'profile' in page and page['profile'] is not None:
            return experiences[:3]
        elif 'all' in page and page['all'] is not None:
            return experiences


class Chat:

    table = 'chat'

    def create(self, data):
        return db.insert(SCHEMA, self.table, [data])

    def update(self, data):
        return db.update(SCHEMA, self.table, [data])

    def get_user_messages(self, receiver_id, sender_id):
        messages = db.sql(f"SELECT * FROM {SCHEMA}.{self.table} WHERE (receiver_id='{receiver_id}' AND sender_id='{sender_id}') OR (receiver_id='{sender_id}' AND sender_id='{receiver_id}') ORDER BY __createdtime__ ASC")
        return format_create_time(messages, many=True)

    def get_unread_messages(self, receiver_id):
        messages = db.sql(f"SELECT * FROM {SCHEMA}.{self.table} WHERE receiver_id='{receiver_id}' AND status='unread' ORDER BY __createdtime__ ASC")
        return messages, len(messages)

    def get_chats(self, user_id):
        messages = db.sql(f"SELECT * FROM {SCHEMA}.{self.table} WHERE receiver_id='{user_id}' GROUP BY sender_id")
        print(messages)
        return format_chat_list(messages)

app/user/forms.py
from email.policy import default
from flask import session
from flask_wtf import FlaskForm
from wtforms import StringField, EmailField, SelectMultipleField, SubmitField, TextAreaField, SelectField, DateField, BooleanField
from wtforms.validators import DataRequired, ValidationError
from app.auth.forms import get_all_users
from app.auth.service import UserService


SKILL_CHOICES = {
    'Backend':['flask', 'expressjs', 'django', 'Laravel', 'Ruby on Rails', 'Spring Boot', 'FastAPI', 'Nextjs', 'Nestjs', 'Nuxtjs'],
    'Frontend':['Reactjs', 'Vuejs', 'Angular', 'Svelte'],
    'Mobile':['Android', 'iOS', 'React Native', 'Flutter', 'Ionic'],
    'Language':['Python', 'Java', 'Javascript', 'Ruby', 'PHP', 'Typescript', 'C', 'C++', 'Go', 'Rust', 'Dart', 'Swift', 'Kotlin'],
    'Database':['PostgreSQL', 'MySQL', 'MongoDB', 'HarperDB', 'Redis', 'SQLite'],
    'Cloud Tech':['Amazon Web Services', 'Google Cloud Platform', 'Digital Ocean', 'Microsoft Azure', 'Linode', 'Netlify', 'Vercel', 'Railway', 'Heroku 🥲'],
    'Container':['Docker', 'Kubernetes']
}

STATUS_CHOICES = [('', 'Select Status'), ('Open to work', 'Open to Work'), ('Busy', 'Busy')]


class ProfileForm(FlaskForm):
    full_name = StringField('Full Name', validators=[DataRequired()])
    email = EmailField('Email', validators=[DataRequired()])
    username = StringField('Username', validators=[DataRequired()])
    skills = SelectMultipleField('Skills', choices=SKILL_CHOICES, validators=[DataRequired()])
    bio = TextAreaField('Bio', validators=[DataRequired()])
    status = SelectField('Select Work Status', choices=STATUS_CHOICES, validators=[DataRequired()])
    submit = SubmitField('Save')

    def validate_email(self, email):
        if len(get_all_users()) != 0:
            user = UserService.get_user_by_attr('email', email.data)
            if user and session['user']['id'] != user[0]['id']:
                raise ValidationError('That email is already registered.')

    def validate_username(self, username):
        if len(get_all_users()) != 0:
            user = UserService.get_user_by_attr('username', username.data)
            if user and session['user']['id'] != user[0]['id']:
                raise ValidationError('That username is taken, Please choose a different one.')


class ExperienceForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    organization = StringField('Organization', validators=[DataRequired()])
    start_date = DateField(format='%Y-%m-%d', validators=[DataRequired()])
    end_date = DateField(format='%Y-%m-%d')
    current = BooleanField('I currently work here', default=False)

    submit = SubmitField('Save')

    def validate_end_date(self, end_date):
        if end_date.data:
            if self.start_date.data > end_date.data:
                raise ValidationError("Start date can't be greater than end date")


class ChatForm(FlaskForm):
    message = StringField('Message', validators=[DataRequired()])

app/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)

from . import routes

app/user/routes.py
from crypt import methods
from flask import render_template, flash, url_for, session, redirect, request
from . import user
from app.auth.service import UserService
from app.auth.decorators import login_required, developer_required
from .forms import ProfileForm, ExperienceForm, ChatForm
from .service import ExperienceService, ProfileService, ChatService
from .decorators import edit_permission_required
from datetime import datetime


@user.route('/profile/<string:username>', methods=['GET', 'POST'])
@login_required
def profile(username):
    user = UserService.get_user_by_attr('username', username)[0]
    profile = ProfileService().get_by_user_id(user['id'])
    experience = []
    form = ProfileForm()
    e_form = ExperienceForm()
    c_form = ChatForm()
    messages = []
    if form.validate_on_submit():
        user_data = {'email':form.email.data, 'username':form.username.data, 'full_name':form.full_name.data}
        UserService().update_user(user['id'], [{'email':form.email.data, 'username':form.username.data, 'full_name':form.full_name.data}])
        ProfileService().update(profile['id'], {'skills':form.skills.data, 'bio':form.bio.data, 'status':form.status.data})
        if user_data['username'] != session['user']['username']:
            flash('Profile updated, please login again.', 'info')
            session.pop('user')
            return redirect(url_for('auth.login'))
        else:
            flash('Profile updated successfully.', 'success')
            return redirect(url_for('user.profile', username=username))
    if request.method == 'GET':
        form.full_name.data = user['full_name']
        form.username.data = user['username']
        form.email.data = user['email']
        form.skills.data = profile['skills'] if 'skills' in profile else None
        form.bio.data = profile['bio'] if 'bio' in profile else None
        form.status.data = profile['status'] if 'status' in profile else None
        experience = ExperienceService().get_by_user_id(
            user['id'], {'profile': True})
        if user['id'] != session['user']['id']:
            messages = ChatService().get_user_messages(user['id'], session['user']['id'])
            for _ in range(len(messages)):
                if messages[_]['receiver_id'] == session['user']['id']:
                    ChatService().update(messages[_]['id'], {'status':'read'})
    return render_template('user/profile.html', user=user, user_profile=profile, form=form, e_form=e_form, experience=experience, profile=True, messages=messages, c_form=c_form)

@user.route('/add-experience', methods=['POST'])
@login_required
@developer_required
def add_experience():
    if request.method == 'POST':
        form = ExperienceForm()
        if form.validate_on_submit():
            experience = {
                'title': form.title.data,
                'organization': form.organization.data,
                'start_date': (form.start_date.data).strftime('%d-%m-%Y'),
                'end_date': (form.end_date.data).strftime('%d-%m-%Y'),
                'current': form.current.data,
                'user_id': session['user']['id']
            }
            ExperienceService().create(experience)
            flash('Experience added successfully', 'success')
            return redirect(request.referrer)
        else:
            if form.errors:
                for error, msg in form.errors.items():
                    flash(msg[0], 'warning')
            return redirect(request.referrer)

@user.route('/experiences/<string:user_id>')
@login_required
@developer_required
def experiences(user_id):
    user = UserService().get_user(user_id)[0]
    experience = ExperienceService().get_by_user_id(user_id, {'all':True})
    form = ExperienceForm()
    return render_template('user/experiences.html', experience=experience, user=user, e_form=form)

@user.route('edit-experience/<string:id>', methods=['GET', 'POST'])
@login_required
@developer_required
@edit_permission_required
def edit_experience(id):
    exp = ExperienceService().get_by_id(id)
    form = ExperienceForm()
    if form.validate_on_submit():
        ExperienceService().update(id, {'title':form.title.data, 'organization':form.organization.data, 
                                        'start_date': (form.start_date.data).strftime('%d-%m-%Y'),
                                        'end_date': (form.end_date.data).strftime('%d-%m-%Y') if form.end_date.data is not None else None, 'current': form.current.data})
        flash('Experience updated successfully.', 'success')
        return redirect(url_for('user.experiences', user_id=exp['user_id']))
    if request.method == 'GET':
        form.title.data = exp['title']
        form.organization.data = exp['organization']
        form.start_date.data = datetime.strptime(exp['start_date'], '%d-%m-%Y')
        form.end_date.data = datetime.strptime(exp['end_date'], '%d-%m-%Y') if exp['end_date'] is not None else None
        form.current.data = exp['current'] if 'current' in exp else False
    return render_template('user/edit-experience.html', exp=exp, e_form=form)

@user.route('message/send/<string:user_id>', methods=['POST'])
@login_required
def send_message(user_id):
    if request.method == 'POST':
        form = ChatForm()
        if form.validate_on_submit():
            data = {
                'receiver_id':user_id,
                'sender_id':session['user']['id'],
                'message':form.message.data,
                'status':'unread'
            }
            ChatService().create(data)
            flash('Message sent successfully.', 'success')
            return redirect(request.referrer)
        else:
            if form.errors:
                for error, msg in form.errors.items():
                    flash(msg[0], 'warning')
            return redirect(request.referrer)

@user.route('chats/<string:user_id>', methods=['GET'])
@login_required
def chats(user_id):
    # messages = ChatService().get_chats(user_id)
    # print(messages)
    messages = []
    return render_template('user/chats.html', messages=messages)

app/templates/user/chats.html
{% extends 'layouts/main-layout.html' %}
{% block content %}
<div class="col-md-12">
    <div class="d-flex align-items-center py-5">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-10 mx-auto">
                    <div class="card shadow-sm rounded">
                        <div class="card-body">
                            <div class="d-flex justify-content-between">
                                <h4 class="mb-3">Chats</h4>
                            </div>
                            <div class="list-group">
                                {% if messages %}
                                    {% for msg in messages %}
                                        <div class="list-group-item list-group-item-action">
                                            <div class="d-flex w-100 justify-content-between">
                                                <h5 class="mb-1">{{msg.sender}}</h5>
                                            </div>
                                            <p class="mb-1">{{msg.status}}</p>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/user/edit-experience.html
{% extends 'layouts/main-layout.html' %}
{% block content %}
<div class="col-md-12">
    <div class="d-flex align-items-center py-5">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-9 mx-auto">
                    <div class="card shadow-sm rounded">
                        <div class="card-body">
                            <div class="d-flex justify-content-between">
                                <h4 class="mb-3">Edit Experience</h4>
                            </div>
                            <form action="" method="post">
                                {{e_form.hidden_tag()}}
                                <div class="form-group mb-3">
                                  <label class="col-form-label">{{e_form.title.label}}</label>
                                  {{e_form.title(class='form-control', placeholder='Title')}}
                                  {% for error in e_form.title.errors %}
                                    <small class="text-danger">{{ error }}</small>
                                  {% endfor %}
                                </div>
                                <div class="form-group mb-3">
                                    <label class="col-form-label">{{e_form.organization.label}}</label>
                                    {{e_form.organization(class='form-control', placeholder='Organization')}}
                                    {% for error in e_form.organization.errors %}
                                      <small class="text-danger">{{ error }}</small>
                                    {% endfor %}
                                </div>
                                <div class="row mb-3">
                                    <div class="col">
                                        <div class="form-group">
                                            <label class="col-form-label">{{e_form.start_date.label}}</label>
                                            {{e_form.start_date(class='form-control')}}
                                            {% for error in e_form.start_date.errors %}
                                              <small class="text-danger">{{ error }}</small>
                                            {% endfor %}
                                        </div>     
                                    </div>
                                    <div class="col">
                                        <div class="form-group">
                                            <label class="col-form-label">{{e_form.end_date.label}}</label>
                                            {{e_form.end_date(class='form-control', id='end-date')}}
                                            {% for error in e_form.end_date.errors %}
                                              <small class="text-danger">{{ error }}</small>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group mb-3">
                                    {{e_form.current(id='current')}}
                                    <label class="col-form-label">{{e_form.current.label}}</label>
                                </div>
                                <div class="row">
                                    <div class="col">
                                      {{e_form.submit(class='btn btn-primary btn-block')}}
                                    </div>
                                    <div class="col">
                                      <button type="button" class="btn btn-outline-info btn-block" onclick="goBack()">Back</button>
                                    </div>
                                </div> 
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block js %}
<script>
    if ($('#current').is(':checked') == true){
        $('#end-date').val('').prop('disabled', true);
    }

    $('#current').change(function(){
        if ($('#current').is(':checked') == true){
            $('#end-date').val('').prop('disabled', true);
        } else {
            $('#end-date').val('').prop('disabled', false);
        }
    });

    function goBack() {
        window.history.back();
    }
</script>
{% endblock js %}

app/templates/user/experience-modal.html
<div class="modal" id="experienceModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-dark">
        <h5 class="modal-title text-light text-center" id="exampleModalLabel">Add Experience</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{{url_for('user.add_experience')}}" method="post">
          {{e_form.hidden_tag()}}
          <div class="form-group mb-3">
            <label class="col-form-label">{{e_form.title.label}}</label>
            {{e_form.title(class='form-control', placeholder='Title')}}
            {% for error in e_form.title.errors %}
              <small class="text-danger">{{ error }}</small>
            {% endfor %}
          </div>
          <div class="form-group mb-3">
              <label class="col-form-label">{{e_form.organization.label}}</label>
              {{e_form.organization(class='form-control', placeholder='Organization')}}
              {% for error in e_form.organization.errors %}
                <small class="text-danger">{{ error }}</small>
              {% endfor %}
          </div>
          <div class="row mb-3">
            <div class="col">
                <div class="form-group">
                    <label class="col-form-label">{{e_form.start_date.label}}</label>
                    {{e_form.start_date(class='form-control')}}
                    {% for error in e_form.start_date.errors %}
                      <small class="text-danger">{{ error }}</small>
                    {% endfor %}
                </div>     
            </div>
            <div class="col">
                <div class="form-group">
                    <label class="col-form-label">{{e_form.end_date.label}}</label>
                    {{e_form.end_date(class='form-control', id='end-date')}}
                    {% for error in e_form.end_date.errors %}
                      <small class="text-danger">{{ error }}</small>
                    {% endfor %}
                </div>
            </div>
          </div>
          <div class="form-group mb-3">
            {{e_form.current(id='current')}}
            <label class="col-form-label">{{e_form.current.label}}</label>
          </div>
          {{e_form.submit(class='btn btn-primary btn-block')}}     
        </form>
      </div>
    </div>
  </div>
</div>

app/templates/user/experiences.html
{% extends 'layouts/main-layout.html' %}
{% block content %}
<div class="col-md-12">
    <div class="d-flex align-items-center py-5">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-10 mx-auto">
                    <div class="card shadow-sm rounded">
                        <div class="card-body">
                            <div class="d-flex justify-content-between">
                                <h4 class="mb-3">Work Experience</h4>
                                {% if current_user.id == user.id %}
                                    <i class="fas fa-plus" data-toggle="modal" data-target="#experienceModal"></i>
                                    {% include 'user/experience-modal.html' %}
                                {% endif %}
                            </div>
                            <div class="list-group">
                                {% if experience %}
                                    {% for exp in experience %}
                                        <div class="list-group-item list-group-item-action">
                                            <div class="d-flex w-100 justify-content-between">
                                                <h5 class="mb-1">{{exp.title}}</h5>
                                                {% if current_user.id == user.id %}
                                                    <small><a href="{{url_for('user.edit_experience', id=exp.id)}}"><i class="fas fa-pencil-alt"></i></a></small>
                                                {% endif %}
                                            </div>
                                            <p class="mb-1">{{exp.organization}}</p>
                                            <small class="text-muted">from {{exp.start_date}} to {% if exp.end_date %}{{exp.end_date}}{% else %}Present{% endif %}</small>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            <div class="clearfix mt-2">
                                <small><a href="{{url_for('user.profile', username=user.username)}}" class="float-right">Back to Profile</a></small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block js %}
<script>
    $('#current').change(function(){
        if ($('#current').is(':checked') == true){
            $('#end-date').prop('disabled', true);
        } else {
            $('#end-date').prop('disabled', false);
        }
    });
</script>
{% endblock js %}

app/templates/user/profile.html
{% extends 'layouts/main-layout.html' %}
{% block content %}

<!-- details page -->
<section class="single section-sm pb-0">
    <div class="container">
        <div class="row">
            <div class="col-lg-5">
                <div class="card rounded shadow-sm mb-3 text-center">
                    <div class="card-body">
                        <h3 class="mb-3">
                            {{user.username}}'s Profile
                        </h3>
                        <div class="mb-3">
                            <img src="https://randomuser.me/api/portraits/men/15.jpg" class="rounded" alt="...">
                        </div>
                        <h5>{{user.full_name}} <span class="badge badge-info">{{user_profile.status}}</span></h5> 
                        <div>
                            <p>
                                {{user_profile.bio}}
                            </p>
                        </div>
                        {% if user_profile.skills %}
                            {% for skill in user_profile.skills %}
                                <span class="badge badge-primary"><a class="text-light" href="{{url_for('auth.index', skill=skill)}}">{{skill}}</a></span>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="card rounded shadow-sm">
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <h4 class="mb-3">Work Experience</h4>
                            {% if current_user.id == user.id %}
                                <i class="fas fa-plus" data-toggle="modal" data-target="#experienceModal"></i>
                                {% include 'user/experience-modal.html' %}
                            {% endif %}
                        </div>
                        <div class="list-group">
                            {% if experience %}
                                {% for exp in experience %}
                                    <div class="list-group-item list-group-item-action">
                                        <div class="d-flex w-100 justify-content-between">
                                            <h5 class="mb-1">{{exp.title}}</h5>
                                            {% if current_user.id == user.id %}
                                                <small><a href="{{url_for('user.edit_experience', id=exp.id)}}"><i class="fas fa-pencil-alt"></i></a></small>
                                            {% endif %}
                                        </div>
                                        <p class="mb-1">{{exp.organization}}</p>
                                        <small class="text-muted">from {{exp.start_date}} to {% if exp.end_date %}{{exp.end_date}}{% else %}Present{% endif %}</small>
                                    </div>
                                {% endfor %}
                                <div class="clearfix mt-2">
                                    <small><a href="{{url_for('user.experiences', user_id=user.id)}}" class="float-right">Show all</a></small>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-7">
                <div class="card rounded shadow-sm">
                    <div class="card-body">
                        {% if current_user.id == user.id %}
                        <h3 class="mb-5">Update Profile</h3>
                        <div class="container">
                            <form action="" method="post">
                                {{form.hidden_tag()}}
                                <div class="form-group mb-3">
                                    <label for="">{{form.full_name.label}}</label>
                                    {{form.full_name(class='form-control rounded', placeholder='Enter your name')}}
                                    {% for error in form.full_name.errors %}
                                        <small class="text-danger">{{ error }}</small>
                                    {% endfor %}
                                </div>
                                <div class="form-group mb-3">
                                    <label for="">{{form.email.label}}</label>
                                    {{form.email(class='form-control rounded', placeholder='Enter your email')}}
                                    {% for error in form.email.errors %}
                                        <small class="text-danger">{{ error }}</small>
                                    {% endfor %}
                                </div>
                                <div class="form-group mb-3">
                                    <label for="">{{form.username.label}}</label>
                                    {{form.username(class='form-control rounded', placeholder='Enter your username')}}
                                    {% for error in form.username.errors %}
                                        <small class="text-danger">{{ error }}</small>
                                    {% endfor %}
                                </div>
                                <div class="form-group mb-3">
                                    <label for="">{{form.skills.label}}</label>
                                    {{form.skills(class='form-control rounded selectpicker', id='skills')}}
                                    {% for error in form.skills.errors %}
                                        <small class="text-danger">{{ error }}</small>
                                    {% endfor %}
                                </div>
                                <div class="form-group mb-3">
                                    <label for="">{{form.bio.label}}</label>
                                    {{form.bio(class='form-control rounded', placeholder='Enter your bio')}}
                                    {% for error in form.bio.errors %}
                                        <small class="text-danger">{{ error }}</small>
                                    {% endfor %}
                                </div>
                                <div class="form-group mb-3">
                                    <label for="">{{form.status.label}}</label>
                                    {{form.status(class='form-control rounded selectpicker')}}
                                    {% for error in form.status.errors %}
                                        <small class="text-danger">{{ error }}</small>
                                    {% endfor %}
                                </div>
                                {{form.submit(class='btn btn-primary btn-block rounded')}}
                            </form>
                        </div>
                        {% else %}
                        <h5 class="mb-3">Message {{user.username}}</h5>
                        <div class="card">
                            <div class="card-body pt-4 bg-grey chat-area">
                                <div class="chat-content">
                                    {% for message in messages %}
                                    <div class="chat {% if message.receiver_id == current_user.id %}chat-left{% endif %}">
                                        <div class="chat-body">
                                            <div class="chat-message">
                                                {{message.message}}
                                                <br>
                                                <sub class="text-light">{{message.__createdtime__}}</sub>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="card-footer">
                                <form action="{{url_for('user.send_message', user_id=user.id)}}" method="post" class="form-row">
                                    {{c_form.hidden_tag()}}
                                    {{c_form.message(class="form-control", placeholder="Enter your message")}}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</section>
<!-- /details page -->
{% endblock content %}

{% block js %}
<script>
    $('#skills').attr("data-live-search","true");

    $('#current').change(function(){
        if ($('#current').is(':checked') == true){
            $('#end-date').prop('disabled', true);
        } else {
            $('#end-date').prop('disabled', false);
        }
    });
</script>
{% endblock js %}